underwater_robot:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    roll_joint1_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_joint1
      pid: {p: 1.0, i: 1.0, d: 0.0}
    # To add more just add them here as the first one
    roll_joint2_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_joint2
      pid: {p: 1.0, i: 1.0, d: 0.0}

    roll_joint3_position_controller:
      type: effort_controllers/JointPositionController
      joint: roll_joint3
      pid: {p: 1.0, i: 1.0, d: 0.0}